var myFullName;
console.log("=======Step 1s=======");
console.log("My full name before intialization",myFullName);
myFullName="Gautami Kale";
console.log("-----After intialization------");
console.log("My full name after intailaization is",myFullName);
myFullName="Saurabh Kale";
console.log("full name after update is",myFullName);
console.log("=======Step 2s========");
var Mylove;
Mylove="i love only js";
console.log("Mylove:",Mylove);
console.log("=======Step 3rd=======");
var firstname ="Gautami";
console.log("firstname",firstname);
var lastname ="kale";
var age ="25";
var address ="sangamner";
var pincode ="345623";
var gender ="female";
var isMarried ="yes";

console.log("lastname",lastname);
console.log("Age",age);
console.log("Address",address);
console.log("Pincode",pincode);
console.log("gender",gender);
console.log("isMarried",isMarried);
